### ISSUE TITLE
Verify what's new in Flask 0.11

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#17]
It seems like Flask is going to change a few things from now on:
https://www.palletsprojects.com/blog/flask-011-released/

Worth making some experiments, before updating the docker image.

**Comment by pdonorio** [comment]
And wonder if flask can play "mypy" with no harm:
https://www.dropbox.com/s/efatwr0pozsargb/PyCon%20mypy%20talk%202016.pdf

**Comment by mdantonio** [comment]
I upgraded flask and successfully tested both backend and frontend

Except for the flask.ext deprecation warning (fixed with the previous commit) i found no problem... The upgrade seems quite safe

I'm unable to fully evaluate the changelog, the following points can be of some interest
- Changes to flask.jsonify (datetime support and top-level arrays serialization)
- support custom JSON mimetypes
- request.json in favour of request.get_json().
- SESSION_REFRESH_EACH_REQUEST (don't used, but it is a mechanism that could be implemented for our tokens)
- Flask will now log by default even if debug is disabled. The log format is now hardcoded but the default log handling can be disabled through the LOGGER_HANDLER_POLICY configuration key.
- flask.g now has pop() and setdefault methods.

**NOTE** request.json (deprecated in favour of request.get_json()) is used in pages.py, this piece of code it is unused now?

**Comment by pdonorio** [comment]
When we have time we should take a look at [this list](https://github.com/humiaozuzu/awesome-flask) found by @mdantonio

**Comment by pdonorio** [comment]
> The upgrade seems quite safe

I will update the image this weekend then

> Changes to flask.jsonify

Finally! I had a lot of errors with this in the past

> SESSION_REFRESH_EACH_REQUEST

how can we use it for tokens?

> flask.g now has pop() and setdefault methods

and we should use it in `server.py`

**Comment by pdonorio** [comment]
> request.json (deprecated in favour of request.get_json()) is used in pages.py, this piece of code it is unused now?

Well we have that forever lasting problem of logging errors. 
If we like how things goes now, we may throw that code away.

**Comment by pdonorio** [comment]
Another note for flask cli (the new one) is:
https://github.com/sloria/flask-konch

**Comment by mdantonio** [comment]
> > SESSION_REFRESH_EACH_REQUEST
> 
> how can we use it for tokens?

I will respond you in the JWT issue

**Comment by mdantonio** [comment]
> Well we have that forever lasting problem of logging errors. 
> If we like how things goes now, we may throw that code away.

So authentication will be from UI directly to API and frontend will be unable to intercept it, right?
I think that we could confirm this simplified schema (since we don't really find a motivation to keep both frontend and backend authenticated).
By removing that code in pages.py we can also remove  security.py? (who contains login_api, logout_api and register_api functions)

(note that we are totally off topic in this issue)

**Comment by pdonorio** [comment]
> we don't really find a motivation to keep both frontend and backend authenticated
> note that we are totally off topic in this issue

Yep to both.
I'll open the issue in restangulask

**Comment by pdonorio** [comment]
Updated images with Flask to the latest version.

I have used [a constraint to block to the current new one](https://github.com/pdonorio/dockerizing/blob/master/python/py3api/Dockerfile#L14) so that we can avoid automatic updates when a new release will come out.

**Comment by pdonorio** [comment]
> flask.g now has pop() and setdefault methods
> and we should use it in server.py

This is the last task, then we can close here

**Comment by pdonorio** [comment]
> And wonder if flask can play "mypy" with no harm

Forget for now :)

**Comment by pdonorio** [comment]
Are we going to get into [flask 0.12](http://flask.pocoo.org/docs/0.12/changelog/#version-0-12) ?

I may use the last refactor as a driver for this too
