### ISSUE TITLE
Generic method to save a graph object with uuid

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#21]
Use the Python uuid library to generate the hash id which should be saved inside the graphdb for a generic object.

Also provide an example of usage.

**Comment by mdantonio** [comment]
The method takes in input a graph Model and an optional dictionary of properties

It automatically adds an `id = getUUID()` so the model must have such property (could be verified the existence or could be made optional)

id property should be somethink like this:

`id = StringProperty(required=True, unique_index=True)`

If `created` and/or `modified` properties are found in the model, they are automatically filled with datetime.now

Then all values found in the properties dictionary are applied

No exception verified, so the caller should do it by it self. To be decided the better strategy about this (I find this approach effective because all my endpoints are decorated with catch exception)

**Comment by mdantonio** [comment]
Example based on the following model:

```
class myModel(StructuredNode):
    id = StringProperty(required=True, unique_index=True)
    name = StringProperty(required=True, unique_index=True)
    description = StringProperty()
    created = DateTimeProperty(required=True)
    modified = DateTimeProperty(required=True)

   myrelation = RelationshipTo('otherModel', 'IS_RELATED_TO', cardinality=ZeroOrMore)
```

node creation:

```
properties = {"name": "My model name", "description": "My model description"}
node = self.graph.createNode(self.graph.myModel, properties)
node.myrelation.connect(otherNode)
```

**Comment by mdantonio** [comment]
If this method can be enough for this issue, you can close it

**Comment by pdonorio** [comment]
That's enough. Will test and use it. And then close the issue.

**Comment by pdonorio** [comment]
Tested and it works great!
