### ISSUE TITLE
JSON standard for API response

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#22]
We might try to apply some pieces of this example:
http://jsonapi.org/

The most important part is the "link"->"self" which should refer to the uuid provided in #21 

Also "relationships" (e.g. parent and replicas) and "attributes" (read `metadata`) might be taken in consideration.

We could become fully compliant in time, in fact the format has already reached the 1.0 version.

**Comment by mdantonio** [comment]
How would you implement this?

a method in base.py that given a model and a list of requested properties returns a json by decorating it with information compliant with standards?

I already follow a similar schema (clearly not following such standards) using the following method:

```
    def getJson(self, instance, *fields):

        data = {}
        for key in fields:

            if hasattr(instance, key):

                attribute = getattr(instance, key)
                # datetime is not json serializable, converting it to string
                if isinstance(attribute, datetime):
                    data[key] = attribute.strftime('%s')
                else:
                    data[key] = attribute
        return data
```

Probabily the code can be improved by using flask.jsonify

Starting from this code we could create somethink like this:

```
data["link"]["self"] = ???
data["type"] = ???
data["id"] = node.id
data["attributes"] = { the dictionary actually returned by the method }
data["relationships"] = ???
```

To be discussed how to retrieve the "???" fields

data["link"]["self"] -> guess from endpoint?
data["type"] -> Model name?
data["relationships"] -> not all relationships should be listed -> list of relationships to inspect as input?

Relationships open some problems, since link, type and relationships fields should be recursively filled also for the related resources

**Comment by pdonorio** [comment]
> I already follow a similar schema

That is looks like a good base to me.

> data["link"]["self"] -> guess from endpoint?

It would be great, but isn't that difficult?

> data["type"] -> Model name?

As default yes, but the developer can specify his own type.

> Relationships open some problems

Ok, it must be skipped for now. We don't have a clear data model to use it.

**Comment by mdantonio** [comment]
Implemented a `formatJsonResponse` base.py that takes as input a list of object instances (e.g. neoModels) and a list of fields and returns the schema discussed above (without relationships)

"data" is filled by using a second method `getJsonResponse` that takes as input a single object instance and returns the json schema.

From my endpoints I cannot use the the general method (the first) but i can use the second one

If you have a use case to test it we can integrate this implementation into your code

**Comment by pdonorio** [comment]
@mdantonio tested the new version which is more compliant.
_VERY IMPORTANT_ this was possible only because we used the GraphDB as a backend service!

Going on hold for now.
To be done in the near future:
- [ ] code jsonapi.org pagination (links: next and last)
- [ ] find a way to get the right uri associated to the right graph object
- [ ] implement self links in related objects

**Comment by pdonorio** [comment]
This issue is waiting for the graphdb to be officially integrated into the B2SAFE service. Without that plugged as backend is not very reasonably doable to walk relationships.

We should also explicit in the code the requirement of the graphdb service to let relationships exist.

**Comment by pdonorio** [comment]
Long time wait
